first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
print("====================")
current_year = input("Enter the current year: ")
birth_year = input("Enter your birth year: ")
age = int(current_year) - int(birth_year)
print("Hello your name is " + first_name + " " + last_name + ".")
print("You are " + str(age) + " years old.")
print("you will be " + str(age + 1) + " years old in 2026.")
print("====================")
print("completed by, John Benites")
print("====================")